apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql-container
          image: mcr.microsoft.com/azure-sql-edge:1.0.4
          ports:
            - containerPort: 1433  # Assuming SQL Server port
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_USERNAME
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc
