apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bXl1c2VybmFtZQ==  # Base64-encoded username
  MONGO_INITDB_ROOT_PASSWORD: bXlwYXNzd29yZA==  # Base64-encoded password
